### ISSUE TITLE
When will be added support for VS 2015

### ISSUE THREAD

**Issue by QuantumDeveloper** [sharpdx/SharpDX#623] opened 2015-08-03 20:08 UTC
For now it is impossible to compile sources using VS 2015.

When you enable support for that version?

**Comment by xoofx** [comment] 2015-08-18 13:53
Could you give more details about "impossible"? I just tested and it is compiling fine here.
Have you installed the Windows 10 SDK 10,0,10240.0 as described on https://github.com/sharpdx/SharpDX#build ?

**Comment by QuantumDeveloper** [comment] 2015-08-18 14:00
Yes, I have SDK version installed, but when I start copiling, it fails with error that version 2015 (14.0) is not supported)

**Comment by xoofx** [comment] 2015-08-18 14:02
I can't reproduce this... Which solution are you trying to compile? Do you compile from VS or msbuild/cmdline?

**Comment by QuantumDeveloper** [comment] 2015-08-18 14:10
I compile from VS main solution - SharpDX. With VS 2013 I have no such issues

**Comment by bdachev** [comment] 2015-08-18 20:49
Hi xoofx, 
I can confirm that on a system with VS 2015 only installed the compilation fails at early stages of preparing to parse include files with the error message that QuantumDeveloper mentions.
In order to make it compile I had to modify Source/Mappings.xml and GccXml.cs files.
You probably have both VS 2013 and 2015 installed on your machine and that combination works even when compilation is done via VS 2015 because header files and compile tools of 2013 exist.
B.

**Comment by xoofx** [comment] 2015-08-19 13:34
Currently, SharpDX doesn't compile with VS 2015 only. You need to have C/C++  runtime headers shipped with VS2013. No ETA when I will have time to look at this...

**Comment by QuantumDeveloper** [comment] 2015-08-19 14:09
@bdachev maybe you could provide necessary fixes for this issue?

**Comment by RobyDX** [comment] 2015-08-19 14:14
just for information. Yesterday compilation worked for me. I've installed VS 2015, not VS 2013 (but I had previously, then I've unistalled to install VS15). 
Yesterday I've installed githhub extension... and now stop compiling. Can be usefull this information? What I must install to compile? Visual C++ 2013 or other components are enough?

**Comment by bdachev** [comment] 2015-08-19 19:39
Hi Guys, I committed in my fork quick and dirty fix to build SharpDX with VS2015 only. It is in vs2015 branch. That configuration will break pure VS2013 build so not good idea to merge in master.

**Comment by QuantumDeveloper** [comment] 2015-08-19 19:47
@bdachev thanks for that.

**Comment by RobyDX** [comment] 2015-08-19 20:20
thx

**Comment by bdachev** [comment] 2015-09-08 08:21
Further to my previous message I was able to compile master branch using VS2015 only. What I was missing before and installed in order to make it work was tools for Window 8.1 development.

**Comment by QuantumDeveloper** [comment] 2015-09-08 08:29
@bdachev thanks for info. Will test your solution.

**Comment by bdachev** [comment] 2016-08-18 08:06
Have you seen my previous comment? Do you have Tools for Window 8.1 installed in VS 2015 installer configuration?

**Comment by Ziflin** [comment] 2016-08-18 13:30
Sorry I wasn't sure if that was the only required fix since there were no other replies. Do you know what it needs from the Tools for Windows 8.1?

**Comment by andrewst** [comment] 2016-08-18 15:16
1. Visual Studio 2013
2. Windows 10 SDK 10.0.10586.0

**Comment by Ziflin** [comment] 2016-08-18 15:18
It seems there is still confusion as @bdachev appears to have it working with VS2015 and just the "Tools for Windows 8.1" option.

**Comment by andrewst** [comment] 2016-08-18 15:25
Yes, it work in VS2015, but must installed VS2013.
In build using absolute path 
https://github.com/sharpdx/SharpDX/blob/master/Source/Mapping.xml#L28

**Comment by bdachev** [comment] 2016-08-18 20:03
I can confirm that VS2013 is NOT needed. Installing VS2015 with "Tools for Windows 8.1" option enabled actually installs C++ compilers and tools that come with VS2013. I just did some tests on a Win 10 + VS2015 only installed and I am able to compile both SharpDX solutions. Make sure 10.0.10586.0 SDK is installed as well.

**Comment by Ziflin** [comment] 2016-08-18 20:10
Awesome. Thanks for the help!

**Closed** 2016-09-07 09:05 UTC
Labels: enhancement
