### ISSUE TITLE
Crash while recording Audio

### ISSUE THREAD

**Issue by ankur4747github** [sharpdx/SharpDX#534] opened 2015-01-15 13:31 UTC
Exception: SharpDX.SharpDXException
Message: HRESULT: [0x88780078], Module: [Unknown], ApiCode: [Unknown/Unknown], Message: Unknown
Stack:
   at SharpDX.Result.CheckError()
   at SharpDX.DirectSound.DSound.CaptureCreate8(Nullable`1 cGuidDeviceRef, DirectSoundCapture dSC8Out, ComObject unkOuterRef)
   at SharpDX.DirectSound.DirectSoundCapture..ctor(Guid device)
   at Accord.DirectSound.AudioCaptureDevice.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by ankur4747github** [comment] 2015-01-16 06:16
its version 2.6.0

**Comment by ArtiomCiumac** [comment] 2015-01-16 20:09
The error code you get means that no sound driver is found.
As I see from stack trace you are calling the constructor with a GUID parameter - make sure it is correct or use the constructor without parameters to use the default device. The constructors of the 'DirectSoundCapture' class are calling the unmanaged [DirectSoundCaptureCreate8](http://msdn.microsoft.com/en-us/library/windows/desktop/microsoft.directx_sdk.reference.directsoundcapturecreate8%28v=vs.85%29.aspx) function.

Try to check if the error reproduces on other computers and if you still believe it is an issue with SharpDX - please provide a sample program that can reproduce it.

You can try to use the following code snippet in a console application to check the list of installed audio capture devices and initialize the class above with the first one:

```
namespace DirectSountCaptureTest
{
    using System;
    using System.Linq;

    class Program
    {
        static void Main(string[] args)
        {
            var devices = SharpDX.DirectSound.DirectSoundCapture.GetDevices();

            foreach (var device in devices)
                Console.WriteLine("{0} '{1}' '{2}'", device.DriverGuid, device.ModuleName, device.Description);

            try
            {
                var dc = new SharpDX.DirectSound.DirectSoundCapture(devices.First().DriverGuid);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }

            Console.ReadLine();
        }
    }
}
```

**Comment by ArtiomCiumac** [comment] 2015-01-16 20:10
I am closing the bug as the error is generated by the unmanaged code and SharpDX just translates the call. I will reopen it if you will provide more information demonstrating that the issue is with SharpDX itself.

**Closed by ArtiomCiumac** 2015-01-16 20:10 UTC
Labels: invalid

**Comment by ankur4747github** [comment] 2015-01-19 06:22
Hi thanx for responding actually I have laptop and that sound driver is working properly, but sometimes it's not working... I understand the problem.. I sent the correct GUID but that driver was stuck or not working at that time this crash happened.. I need some proper handle exceptions that handles this crash and say driver missing

Thanku Ankur
