### ISSUE TITLE
PerPrimitive antialiasing not working for offscreen rendering in Direct2D.

### ISSUE THREAD

**Issue by Gavin-Williams** [sharpdx/SharpDX#550] opened 2015-02-17 17:33 UTC
I'm not 100% sure yet, as I'm just starting to work with Direct2D, but I'm pretty sure that PerPrimitive anti-aliasing isn't working when I render to an offscreen texture.

Edit: It may be that offscreen rendering doesn't support anti-aliasing, but I haven't confirmed this yet.

**Comment by xoofx** [comment] 2015-04-01 23:42
This is most likely a usage issue/or a limitation of Direct2D, so I'm closing this. (unless you are not able to reproduce this with C++ code)

**Closed by xoofx** 2015-04-01 23:42 UTC
